<?php

/***************************************************************
* Extension Manager/Repository config file for ext "ext1".
*
* Generated by ext 20-03-2013 14:50
*
* https://github.com/t3elmar/Ext
***************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'user' => 't3elmar',
  'version' => '1.1.0',
);

?>